import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from 'ws';
import * as schema from './shared/schema';

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL must be set');
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle({ client: pool, schema });

const hadiths = [
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 3560', narrator: 'Aisha', grade: 'sahih', category: 'character', englishTranslation: 'Aisha reported: Whenever the Messenger of Allah (ﷺ) was given the choice between two matters, he would choose the easier of the two, as long as it was not sinful. If it was sinful, he would be the furthest of people from it.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6092', narrator: 'Aisha', grade: 'sahih', category: 'character', englishTranslation: 'Aisha reported: I never saw the Prophet (ﷺ) laughing to an extent that one could see his palate; he always used to smile only.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 3559', narrator: 'Abdullah ibn Amr', grade: 'sahih', category: 'character', englishTranslation: 'Abdullah ibn Amr reported: The Prophet (ﷺ) was neither a person who used obscene language nor one who spoke it. He used to say: The best amongst you are those who have the best manners and character.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6089', narrator: 'Jarir ibn Abdullah', grade: 'sahih', category: 'character', englishTranslation: 'Jarir ibn Abdullah reported: The Messenger of Allah (ﷺ) did not screen himself from me since I embraced Islam, and whenever he saw me, he would receive me with a smile.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6114', narrator: 'Abu Huraira', grade: 'sahih', category: 'character', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: The strong is not the one who overcomes people by his strength, but the strong is the one who controls himself while in anger.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6094', narrator: 'Abdullah ibn Masud', grade: 'sahih', category: 'character', englishTranslation: 'Abdullah ibn Masud reported: The Prophet (ﷺ) said: Truthfulness leads to righteousness, and righteousness leads to Paradise. Falsehood leads to wickedness, and wickedness leads to the Fire.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6066', narrator: 'Abu Huraira', grade: 'sahih', category: 'character', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Avoid suspicion, for suspicion is the worst of false tales. Do not seek faults, do not spy, do not envy, do not hate, do not turn away. Be brothers, O servants of Allah.', arabicText: '' },
  { collection: 'tirmidhi', reference: 'Jami at-Tirmidhi 2002', narrator: 'Abu Ad-Darda', grade: 'sahih', category: 'character', englishTranslation: "Abu Ad-Darda reported: The Messenger of Allah (ﷺ) said: Nothing is heavier on the believer's scale on the Day of Judgment than good character. Verily Allah hates the one who is obscene and shameless.", arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6129', narrator: 'Anas ibn Malik', grade: 'sahih', category: 'character', englishTranslation: 'Anas ibn Malik reported: The Prophet (ﷺ) used to mix with us to the extent that he would say to a younger brother of mine: O Abu Umair, what did the Nughair (small bird) do?', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2626', narrator: 'Abu Dharr', grade: 'sahih', category: 'character', englishTranslation: 'Abu Dharr reported: The Messenger of Allah (ﷺ) said: Do not consider any good deed insignificant, even meeting your brother with a cheerful face.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6927', narrator: 'Aisha', grade: 'sahih', category: 'character', englishTranslation: 'Aisha reported: The Messenger of Allah (ﷺ) said: Allah is kind and lenient and loves gentleness in all matters.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6203', narrator: 'Anas ibn Malik', grade: 'sahih', category: 'character', englishTranslation: 'Anas ibn Malik reported: The Messenger of Allah (ﷺ) had the best character of all people.', arabicText: '' },
  { collection: 'malik', reference: 'Muwatta Malik 47:8', narrator: 'Malik ibn Anas', grade: 'sahih', category: 'character', englishTranslation: 'It was reported: The Messenger of Allah (ﷺ) said: I was sent to perfect good character.', arabicText: '' },
  { collection: 'tirmidhi', reference: 'Jami at-Tirmidhi 1924', narrator: 'Abdullah ibn Amr', grade: 'sahih', category: 'kindness', englishTranslation: 'Abdullah ibn Amr reported: The Messenger of Allah (ﷺ) said: The merciful are shown mercy by the Most Merciful. Be merciful to those on earth, and the One above the heavens will be merciful to you.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 13', narrator: 'Anas ibn Malik', grade: 'sahih', category: 'kindness', englishTranslation: 'Anas ibn Malik reported: The Prophet (ﷺ) said: None of you truly believes until he loves for his brother what he loves for himself.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5373', narrator: 'Abu Musa al-Ashari', grade: 'sahih', category: 'kindness', englishTranslation: 'Abu Musa al-Ashari reported: The Prophet (ﷺ) said: Give food to the hungry, visit the sick, and free the captive.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2699a', narrator: 'Abu Huraira', grade: 'sahih', category: 'kindness', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: Whoever relieves a Muslim of a burden from the burdens of this world, Allah will relieve him of a burden from the burdens of the Day of Resurrection.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6130', narrator: 'Aisha', grade: 'sahih', category: 'kindness', englishTranslation: 'Aisha reported: When the Messenger of Allah (ﷺ) entered our dwelling place, my girl friends would hide themselves. He would call them to join and play with me, and they would come.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 2466', narrator: 'Abu Huraira', grade: 'sahih', category: 'kindness', englishTranslation: "Abu Huraira reported: The Prophet (ﷺ) said: A man saw a dog eating mud from the pangs of thirst. So the man took his shoe and filled it with water until he quenched the dog's thirst. So Allah thanked him and admitted him to Paradise.", arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6018', narrator: 'Abu Huraira', grade: 'sahih', category: 'kindness', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Whoever believes in Allah and the Last Day should not harm his neighbour. Whoever believes in Allah and the Last Day should honour his guest. Whoever believes in Allah and the Last Day should speak good or remain silent.', arabicText: '' },
  { collection: 'tirmidhi', reference: 'Jami at-Tirmidhi 3895', narrator: 'Aisha', grade: 'sahih', category: 'kindness', englishTranslation: 'Aisha reported: The Messenger of Allah (ﷺ) said: The best of you is the best to his wives, and I am the best of you to my wives.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2564a', narrator: 'Abu Huraira', grade: 'sahih', category: 'kindness', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: Verily, Allah does not look at your appearance or wealth, but rather He looks at your hearts and your deeds.', arabicText: '' },
  { collection: 'ibnmajah', reference: 'Sunan Ibn Majah 224', narrator: 'Anas ibn Malik', grade: 'sahih', category: 'knowledge', englishTranslation: 'Anas ibn Malik reported: The Messenger of Allah (ﷺ) said: Seeking knowledge is a duty upon every Muslim.', arabicText: '' },
  { collection: 'tirmidhi', reference: 'Jami at-Tirmidhi 2516', narrator: 'Ibn Abbas', grade: 'sahih', category: 'knowledge', englishTranslation: 'Ibn Abbas reported: The Messenger of Allah (ﷺ) said: O young man, I will teach you some words. Be mindful of Allah and He will protect you. Be mindful of Allah and you will find Him before you.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 1631', narrator: 'Abu Huraira', grade: 'sahih', category: 'knowledge', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: When a man dies, his deeds come to an end except three: a continuing charity, knowledge that is benefited from, and a righteous child who prays for him.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 71', narrator: 'Muawiyah', grade: 'sahih', category: 'knowledge', englishTranslation: 'Muawiyah reported: The Prophet (ﷺ) said: If Allah wants good for a person, He gives him understanding of the religion.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 79', narrator: 'Abu Musa al-Ashari', grade: 'sahih', category: 'knowledge', englishTranslation: 'Abu Musa al-Ashari reported: The Prophet (ﷺ) said: The guidance and knowledge with which Allah has sent me is like abundant rain falling on the earth; some of it was fertile and absorbed the rain and brought forth vegetation and grass in abundance.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6412', narrator: 'Ibn Abbas', grade: 'sahih', category: 'knowledge', englishTranslation: 'Ibn Abbas reported: The Prophet (ﷺ) said: There are two blessings which many people lose: good health and free time.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 1', narrator: 'Umar ibn al-Khattab', grade: 'sahih', category: 'worship', englishTranslation: 'Umar ibn al-Khattab reported: I heard the Messenger of Allah (ﷺ) say: Deeds are judged by their intentions, and every person will have what he intended.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 8', narrator: 'Ibn Umar', grade: 'sahih', category: 'worship', englishTranslation: 'Ibn Umar reported: The Messenger of Allah (ﷺ) said: Islam is built upon five pillars: the testimony that there is no god but Allah and that Muhammad is His Messenger, establishing prayer, paying zakat, making the pilgrimage to the House, and fasting in Ramadan.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 223', narrator: 'Abu Malik al-Ashari', grade: 'sahih', category: 'worship', englishTranslation: 'Abu Malik al-Ashari reported: The Messenger of Allah (ﷺ) said: Cleanliness is half of faith. Al-hamdulillah fills the scale. SubhanAllah and al-hamdulillah fill what is between the heavens and the earth.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6502', narrator: 'Abu Huraira', grade: 'sahih', category: 'worship', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: Allah said: I will declare war against him who shows hostility to a pious worshipper of Mine. The most beloved thing with which My slave comes nearer to Me is what I have made obligatory upon him.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6464', narrator: 'Aisha', grade: 'sahih', category: 'worship', englishTranslation: 'Aisha reported: The Messenger of Allah (ﷺ) said: Do good deeds properly, sincerely and moderately. Always adopt a middle, moderate, regular course, whereby you will reach your target.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 1145', narrator: 'Abu Huraira', grade: 'sahih', category: 'worship', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Our Lord descends to the lowest heaven during the last third of the night, saying: Who calls upon Me, that I may answer him? Who asks of Me, that I may give him? Who seeks My forgiveness, that I may forgive him?', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6116', narrator: 'Abu Huraira', grade: 'sahih', category: 'worship', englishTranslation: 'Abu Huraira reported: A man said to the Prophet (ﷺ): Advise me. He said: Do not become angry. The man repeated his request several times, and each time the Prophet (ﷺ) said: Do not become angry.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 7392', narrator: 'Abu Huraira', grade: 'sahih', category: 'worship', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Allah has ninety-nine names, one hundred less one. Whoever enumerates them will enter Paradise.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5971', narrator: 'Abu Huraira', grade: 'sahih', category: 'family', englishTranslation: 'Abu Huraira reported: A man came to the Prophet (ﷺ) and asked: Who among the people is most deserving of my good company? He said: Your mother. The man asked: Then who? He said: Your mother. Then who? He said: Your mother. Then who? He said: Your father.', arabicText: '' },
  { collection: 'tirmidhi', reference: 'Jami at-Tirmidhi 1162', narrator: 'Abu Huraira', grade: 'sahih', category: 'family', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: The most complete of the believers in faith is the one with the best character, and the best of you are those who are best to their women.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5970', narrator: 'Abdullah ibn Masud', grade: 'sahih', category: 'family', englishTranslation: 'Abdullah ibn Masud reported: I asked the Prophet (ﷺ): Which deed is most beloved to Allah? He said: Prayer at its proper time. I asked: Then what? He said: Kindness to parents. I asked: Then what? He said: Jihad in the way of Allah.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5985', narrator: 'Abu Huraira', grade: 'sahih', category: 'family', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Whoever wishes to have his provision expanded and his life prolonged, let him maintain ties of kinship.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5997', narrator: 'Abu Huraira', grade: 'sahih', category: 'family', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) kissed his grandson Hasan ibn Ali while al-Aqra ibn Habis was sitting nearby. Al-Aqra said: I have ten children and have never kissed any of them. The Prophet (ﷺ) looked at him and said: Whoever does not show mercy will not be shown mercy.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6038', narrator: 'Anas ibn Malik', grade: 'sahih', category: 'family', englishTranslation: 'Anas ibn Malik reported: I served the Prophet (ﷺ) for ten years. He never said to me Uff, nor said about a thing I had done: Why did you do that? And never said about a thing I had left: Why did you not do that?', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2588', narrator: 'Abu Huraira', grade: 'sahih', category: 'charity', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: Charity does not decrease wealth. No one forgives another except that Allah increases his honour. No one humbles himself for the sake of Allah except that Allah raises his status.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 1010', narrator: 'Abu Huraira', grade: 'sahih', category: 'charity', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Every day two angels descend. One says: O Allah, give recompense to every person who spends in Your cause. The other says: O Allah, give ruin to every miser.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 1429', narrator: 'Ibn Umar', grade: 'sahih', category: 'charity', englishTranslation: 'Ibn Umar reported: The Prophet (ﷺ) said: The upper hand is better than the lower hand. The upper hand is the one that gives, and the lower hand is the one that receives.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 2989', narrator: 'Abu Huraira', grade: 'sahih', category: 'charity', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Removing a harmful thing from the road is an act of charity.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6021', narrator: 'Jabir ibn Abdullah', grade: 'sahih', category: 'charity', englishTranslation: 'Jabir ibn Abdullah reported: The Prophet (ﷺ) said: Every act of kindness is a charity.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2580', narrator: 'Abdullah ibn Umar', grade: 'sahih', category: 'community', englishTranslation: "Abdullah ibn Umar reported: The Messenger of Allah (ﷺ) said: A Muslim is the brother of a Muslim. He does not oppress him, nor does he forsake him, nor does he hand him over to an enemy. Whoever fulfills his brother's need, Allah will fulfill his need.", arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2162a', narrator: 'Abu Huraira', grade: 'sahih', category: 'community', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: The rights of a Muslim upon another Muslim are five: returning the greeting of salam, visiting the sick, following the funeral procession, accepting the invitation, and replying to the one who sneezes and praises Allah.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6011', narrator: 'An-Numan ibn Bashir', grade: 'sahih', category: 'community', englishTranslation: 'An-Numan ibn Bashir reported: The Messenger of Allah (ﷺ) said: The believers in their mutual mercy, love, and kindness are like one body. If one part of the body suffers, the whole body shares the sleeplessness and fever.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2999', narrator: 'Suhaib', grade: 'sahih', category: 'patience', englishTranslation: 'Suhaib reported: The Messenger of Allah (ﷺ) said: Wondrous is the affair of the believer, for all of his affairs are good. If something good happens to him, he is grateful and that is good for him. If something harmful happens to him, he is patient and that is good for him.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5641', narrator: 'Abu Huraira', grade: 'sahih', category: 'patience', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: No fatigue, illness, anxiety, sorrow, harm, or sadness afflicts a Muslim, not even a thorn that pricks him, except that Allah expiates some of his sins through it.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 1302', narrator: 'Anas ibn Malik', grade: 'sahih', category: 'patience', englishTranslation: 'Anas ibn Malik reported: The Prophet (ﷺ) said: The real patience is at the first stroke of a calamity.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 6406', narrator: 'Abu Huraira', grade: 'sahih', category: 'patience', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Two phrases are light on the tongue, heavy on the scale, and beloved to the Most Merciful: SubhanAllahi wa bihamdih, SubhanAllahil-Adheem.', arabicText: '' },
  { collection: 'adab', reference: 'Al-Adab Al-Mufrad 479', narrator: 'Anas ibn Malik', grade: 'sahih', category: 'patience', englishTranslation: 'Anas ibn Malik reported: The Prophet (ﷺ) said: If the Final Hour comes while one of you has a palm-cutting in his hand and is able to plant it before the Hour comes, let him plant it.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5678', narrator: 'Abu Huraira', grade: 'sahih', category: 'health', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: Allah has not sent down any disease except that He has also sent down the cure for it.', arabicText: '' },
  { collection: 'bukhari', reference: 'Sahih al-Bukhari 5392', narrator: 'Abu Huraira', grade: 'sahih', category: 'health', englishTranslation: 'Abu Huraira reported: The Prophet (ﷺ) said: The food of two people is sufficient for three, and the food of three is sufficient for four.', arabicText: '' },
  { collection: 'ibnmajah', reference: 'Sunan Ibn Majah 3349', narrator: 'Miqdam ibn Madikarib', grade: 'sahih', category: 'health', englishTranslation: 'Miqdam ibn Madikarib reported: The Messenger of Allah (ﷺ) said: No human being has ever filled a vessel worse than his stomach. A few mouthfuls are sufficient to keep his back straight. But if he must eat more, then one third for his food, one third for his drink, and one third for his breathing.', arabicText: '' },
  { collection: 'muslim', reference: 'Sahih Muslim 2664', narrator: 'Abu Huraira', grade: 'sahih', category: 'health', englishTranslation: 'Abu Huraira reported: The Messenger of Allah (ﷺ) said: A strong believer is better and more beloved to Allah than a weak believer, and there is good in both.', arabicText: '' },
];

async function main() {
  console.log(`Inserting ${hadiths.length} hadiths...`);
  await db.insert(schema.hadiths).values(hadiths);
  const result = await db.select({ count: schema.hadiths.id }).from(schema.hadiths);
  console.log(`Done. Total hadiths in database: ${result.length}`);
  await pool.end();
}

main().catch((err) => { console.error(err); process.exit(1); });
