uploads = []
outputs = []

[[generated]]
id = "-5XToBQNJ9CoowTRtZI4M"
uri = "file://attached_assets/salah/takbir.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_Ge24udziuhS4QYVTkeuk"
uri = "file://attached_assets/salah/qiyam.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sKToprB2xy7OZCC7Z9jdC"
uri = "file://attached_assets/salah/ruku.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ivFOZdrrjUFsU1kGbsFsW"
uri = "file://attached_assets/salah/sujood.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dHLIo7EgaSQ0XecSKNvK-"
uri = "file://attached_assets/salah/jalsah.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yAse3nnFH2tAdbkNk3Rkj"
uri = "file://attached_assets/salah/tasleem.png"
type = "image"
title = "generated_image"
