// Islamic phrase dictionary for instant translations
// These common phrases appear frequently in khutbahs and can be translated without AI

export const islamicPhrasesData = [
  // ==================== DHIKR (Remembrance) ====================
  { arabic: "بسم الله الرحمن الرحيم", english: "In the name of Allah, the Most Gracious, the Most Merciful", category: "dhikr", frequency: "frequent" },
  { arabic: "الحمد لله", english: "All praise is due to Allah", category: "dhikr", frequency: "frequent" },
  { arabic: "الحمد لله رب العالمين", english: "All praise is due to Allah, Lord of the worlds", category: "dhikr", frequency: "frequent" },
  { arabic: "سبحان الله", english: "Glory be to Allah", category: "dhikr", frequency: "frequent" },
  { arabic: "سبحان الله وبحمده", english: "Glory be to Allah and His is the praise", category: "dhikr", frequency: "common" },
  { arabic: "سبحان الله العظيم", english: "Glory be to Allah, the Magnificent", category: "dhikr", frequency: "common" },
  { arabic: "الله أكبر", english: "Allah is the Greatest", category: "dhikr", frequency: "frequent" },
  { arabic: "لا إله إلا الله", english: "There is no god but Allah", category: "dhikr", frequency: "frequent" },
  { arabic: "لا إله إلا الله محمد رسول الله", english: "There is no god but Allah, Muhammad is the Messenger of Allah", category: "dhikr", frequency: "frequent" },
  { arabic: "أستغفر الله", english: "I seek forgiveness from Allah", category: "dhikr", frequency: "frequent" },
  { arabic: "أستغفر الله العظيم", english: "I seek forgiveness from Allah, the Magnificent", category: "dhikr", frequency: "common" },
  { arabic: "لا حول ولا قوة إلا بالله", english: "There is no power or strength except with Allah", category: "dhikr", frequency: "common" },
  { arabic: "لا حول ولا قوة إلا بالله العلي العظيم", english: "There is no power or strength except with Allah, the Most High, the Most Great", category: "dhikr", frequency: "common" },
  { arabic: "سبحان الله والحمد لله ولا إله إلا الله والله أكبر", english: "Glory be to Allah, all praise is due to Allah, there is no god but Allah, and Allah is the Greatest", category: "dhikr", frequency: "common" },
  { arabic: "حسبنا الله ونعم الوكيل", english: "Allah is sufficient for us and He is the best disposer of affairs", category: "dhikr", frequency: "common" },
  { arabic: "ماشاء الله", english: "What Allah has willed", category: "dhikr", frequency: "frequent" },
  { arabic: "إن شاء الله", english: "If Allah wills", category: "dhikr", frequency: "frequent" },
  { arabic: "توكلت على الله", english: "I put my trust in Allah", category: "dhikr", frequency: "common" },
  { arabic: "بارك الله فيك", english: "May Allah bless you", category: "dhikr", frequency: "common" },
  { arabic: "بارك الله فيكم", english: "May Allah bless you all", category: "dhikr", frequency: "common" },
  { arabic: "جزاك الله خيرا", english: "May Allah reward you with goodness", category: "dhikr", frequency: "common" },
  { arabic: "جزاكم الله خيرا", english: "May Allah reward you all with goodness", category: "dhikr", frequency: "common" },
  { arabic: "يا رب", english: "O Lord", category: "dhikr", frequency: "frequent" },
  { arabic: "يا الله", english: "O Allah", category: "dhikr", frequency: "frequent" },
  { arabic: "اللهم آمين", english: "O Allah, amen", category: "dhikr", frequency: "frequent" },
  { arabic: "آمين", english: "Amen", category: "dhikr", frequency: "frequent" },
  { arabic: "تبارك الله", english: "Blessed is Allah", category: "dhikr", frequency: "common" },
  { arabic: "أعوذ بالله من الشيطان الرجيم", english: "I seek refuge in Allah from the accursed Satan", category: "dhikr", frequency: "frequent" },
  { arabic: "أعوذ بالله", english: "I seek refuge in Allah", category: "dhikr", frequency: "common" },
  
  // ==================== GREETINGS ====================
  { arabic: "السلام عليكم", english: "Peace be upon you", category: "greetings", frequency: "frequent" },
  { arabic: "السلام عليكم ورحمة الله", english: "Peace be upon you and the mercy of Allah", category: "greetings", frequency: "frequent" },
  { arabic: "السلام عليكم ورحمة الله وبركاته", english: "Peace be upon you and the mercy and blessings of Allah", category: "greetings", frequency: "frequent" },
  { arabic: "وعليكم السلام", english: "And upon you be peace", category: "greetings", frequency: "frequent" },
  { arabic: "وعليكم السلام ورحمة الله وبركاته", english: "And upon you be peace and the mercy and blessings of Allah", category: "greetings", frequency: "frequent" },
  { arabic: "أهلا وسهلا", english: "Welcome", category: "greetings", frequency: "common" },
  { arabic: "مرحبا", english: "Hello/Welcome", category: "greetings", frequency: "common" },
  
  // ==================== HONORIFICS ====================
  { arabic: "صلى الله عليه وسلم", english: "(peace be upon him)", category: "honorific", frequency: "frequent" },
  { arabic: "صلى الله عليه وآله وسلم", english: "(peace be upon him and his family)", category: "honorific", frequency: "common" },
  { arabic: "عليه السلام", english: "(peace be upon him)", category: "honorific", frequency: "frequent" },
  { arabic: "عليها السلام", english: "(peace be upon her)", category: "honorific", frequency: "common" },
  { arabic: "عليهم السلام", english: "(peace be upon them)", category: "honorific", frequency: "common" },
  { arabic: "رضي الله عنه", english: "(may Allah be pleased with him)", category: "honorific", frequency: "frequent" },
  { arabic: "رضي الله عنها", english: "(may Allah be pleased with her)", category: "honorific", frequency: "common" },
  { arabic: "رضي الله عنهم", english: "(may Allah be pleased with them)", category: "honorific", frequency: "common" },
  { arabic: "رحمه الله", english: "(may Allah have mercy on him)", category: "honorific", frequency: "common" },
  { arabic: "رحمها الله", english: "(may Allah have mercy on her)", category: "honorific", frequency: "common" },
  { arabic: "حفظه الله", english: "(may Allah preserve him)", category: "honorific", frequency: "common" },
  { arabic: "سبحانه وتعالى", english: "(glorified and exalted is He)", category: "honorific", frequency: "frequent" },
  { arabic: "عز وجل", english: "(the Mighty and Majestic)", category: "honorific", frequency: "frequent" },
  { arabic: "جل جلاله", english: "(may His majesty be glorified)", category: "honorific", frequency: "common" },
  { arabic: "تبارك وتعالى", english: "(blessed and exalted is He)", category: "honorific", frequency: "common" },
  
  // ==================== KHUTBAH OPENINGS ====================
  { arabic: "الحمد لله نحمده ونستعينه ونستغفره", english: "All praise is due to Allah, we praise Him, seek His help, and seek His forgiveness", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "إن الحمد لله نحمده ونستعينه ونستغفره", english: "Indeed, all praise is due to Allah, we praise Him, seek His help, and seek His forgiveness", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أما بعد", english: "To proceed", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أيها المسلمون", english: "O Muslims", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أيها المؤمنون", english: "O believers", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أيها الإخوة", english: "O brothers", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أيها الناس", english: "O people", category: "khutbah_formula", frequency: "common" },
  { arabic: "عباد الله", english: "Servants of Allah", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "يا عباد الله", english: "O servants of Allah", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "اتقوا الله", english: "Fear Allah", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "اتقوا الله حق تقاته", english: "Fear Allah as He should be feared", category: "khutbah_formula", frequency: "common" },
  { arabic: "فاتقوا الله", english: "So fear Allah", category: "khutbah_formula", frequency: "common" },
  { arabic: "أقول قولي هذا وأستغفر الله لي ولكم", english: "I say this word of mine and I seek forgiveness from Allah for me and for you", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أقول قولي هذا", english: "I say this word of mine", category: "khutbah_formula", frequency: "common" },
  { arabic: "وأستغفر الله لي ولكم", english: "And I seek forgiveness from Allah for me and for you", category: "khutbah_formula", frequency: "common" },
  { arabic: "والسلام عليكم ورحمة الله وبركاته", english: "And peace be upon you and the mercy and blessings of Allah", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أقيموا الصلاة", english: "Establish the prayer", category: "khutbah_formula", frequency: "frequent" },
  { arabic: "أقم الصلاة", english: "Establish the prayer", category: "khutbah_formula", frequency: "common" },
  
  // ==================== COMMON QURANIC PHRASES ====================
  { arabic: "قال الله تعالى", english: "Allah the Most High said", category: "quran", frequency: "frequent" },
  { arabic: "يقول الله تعالى", english: "Allah the Most High says", category: "quran", frequency: "frequent" },
  { arabic: "كما قال الله تعالى", english: "As Allah the Most High said", category: "quran", frequency: "common" },
  { arabic: "قال تعالى", english: "The Most High said", category: "quran", frequency: "frequent" },
  { arabic: "يقول تعالى", english: "The Most High says", category: "quran", frequency: "frequent" },
  { arabic: "في كتابه الكريم", english: "In His Noble Book", category: "quran", frequency: "common" },
  { arabic: "في القرآن الكريم", english: "In the Noble Quran", category: "quran", frequency: "common" },
  { arabic: "صدق الله العظيم", english: "Allah the Almighty has spoken the truth", category: "quran", frequency: "frequent" },
  { arabic: "والله يقول الحق وهو يهدي السبيل", english: "And Allah speaks the truth and He guides to the right path", category: "quran", frequency: "common" },
  { arabic: "يا أيها الذين آمنوا", english: "O you who believe", category: "quran", frequency: "frequent" },
  { arabic: "يا أيها الناس", english: "O mankind", category: "quran", frequency: "frequent" },
  { arabic: "إنا لله وإنا إليه راجعون", english: "Indeed, we belong to Allah and to Him we shall return", category: "quran", frequency: "common" },
  { arabic: "ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة", english: "Our Lord, give us good in this world and good in the Hereafter", category: "quran", frequency: "common" },
  { arabic: "وقنا عذاب النار", english: "And protect us from the punishment of the Fire", category: "quran", frequency: "common" },
  { arabic: "إن الله مع الصابرين", english: "Indeed, Allah is with the patient", category: "quran", frequency: "common" },
  { arabic: "إن الله يحب المحسنين", english: "Indeed, Allah loves those who do good", category: "quran", frequency: "common" },
  { arabic: "إن الله يحب التوابين ويحب المتطهرين", english: "Indeed, Allah loves those who repent and loves those who purify themselves", category: "quran", frequency: "common" },
  { arabic: "ولا تقنطوا من رحمة الله", english: "And do not despair of the mercy of Allah", category: "quran", frequency: "common" },
  { arabic: "إن رحمة الله قريب من المحسنين", english: "Indeed, the mercy of Allah is near to those who do good", category: "quran", frequency: "common" },
  
  // ==================== HADITH FORMULAS ====================
  { arabic: "قال رسول الله صلى الله عليه وسلم", english: "The Messenger of Allah (peace be upon him) said", category: "hadith_formula", frequency: "frequent" },
  { arabic: "قال النبي صلى الله عليه وسلم", english: "The Prophet (peace be upon him) said", category: "hadith_formula", frequency: "frequent" },
  { arabic: "عن النبي صلى الله عليه وسلم", english: "From the Prophet (peace be upon him)", category: "hadith_formula", frequency: "frequent" },
  { arabic: "في الحديث الشريف", english: "In the noble hadith", category: "hadith_formula", frequency: "common" },
  { arabic: "في الحديث القدسي", english: "In the sacred hadith", category: "hadith_formula", frequency: "common" },
  { arabic: "رواه البخاري", english: "Narrated by Bukhari", category: "hadith_formula", frequency: "common" },
  { arabic: "رواه مسلم", english: "Narrated by Muslim", category: "hadith_formula", frequency: "common" },
  { arabic: "رواه البخاري ومسلم", english: "Narrated by Bukhari and Muslim", category: "hadith_formula", frequency: "common" },
  { arabic: "متفق عليه", english: "Agreed upon (by Bukhari and Muslim)", category: "hadith_formula", frequency: "common" },
  { arabic: "حديث صحيح", english: "Authentic hadith", category: "hadith_formula", frequency: "common" },
  
  // ==================== PRAYER TERMS ====================
  { arabic: "الصلاة", english: "The prayer/salah", category: "prayer", frequency: "frequent" },
  { arabic: "صلاة الفجر", english: "Fajr prayer", category: "prayer", frequency: "common" },
  { arabic: "صلاة الظهر", english: "Dhuhr prayer", category: "prayer", frequency: "common" },
  { arabic: "صلاة العصر", english: "Asr prayer", category: "prayer", frequency: "common" },
  { arabic: "صلاة المغرب", english: "Maghrib prayer", category: "prayer", frequency: "common" },
  { arabic: "صلاة العشاء", english: "Isha prayer", category: "prayer", frequency: "common" },
  { arabic: "صلاة الجمعة", english: "Friday prayer/Jumu'ah", category: "prayer", frequency: "frequent" },
  { arabic: "يوم الجمعة", english: "Friday", category: "prayer", frequency: "frequent" },
  { arabic: "الجمعة المباركة", english: "Blessed Friday", category: "prayer", frequency: "common" },
  { arabic: "صلاة العيد", english: "Eid prayer", category: "prayer", frequency: "common" },
  { arabic: "صلاة التراويح", english: "Taraweeh prayer", category: "prayer", frequency: "common" },
  { arabic: "الوضوء", english: "Ablution/Wudu", category: "prayer", frequency: "common" },
  { arabic: "الغسل", english: "Ritual bath/Ghusl", category: "prayer", frequency: "common" },
  { arabic: "السجود", english: "Prostration/Sujood", category: "prayer", frequency: "common" },
  { arabic: "الركوع", english: "Bowing/Ruku", category: "prayer", frequency: "common" },
  { arabic: "القيام", english: "Standing/Qiyam", category: "prayer", frequency: "common" },
  
  // ==================== ISLAMIC CONCEPTS ====================
  { arabic: "التوحيد", english: "Monotheism/Tawheed", category: "concept", frequency: "common" },
  { arabic: "الإيمان", english: "Faith/Iman", category: "concept", frequency: "frequent" },
  { arabic: "الإسلام", english: "Islam/Submission", category: "concept", frequency: "frequent" },
  { arabic: "الإحسان", english: "Excellence/Ihsan", category: "concept", frequency: "common" },
  { arabic: "التقوى", english: "God-consciousness/Taqwa", category: "concept", frequency: "frequent" },
  { arabic: "الصبر", english: "Patience/Sabr", category: "concept", frequency: "frequent" },
  { arabic: "الشكر", english: "Gratitude/Shukr", category: "concept", frequency: "common" },
  { arabic: "التوبة", english: "Repentance/Tawbah", category: "concept", frequency: "frequent" },
  { arabic: "الاستغفار", english: "Seeking forgiveness/Istighfar", category: "concept", frequency: "common" },
  { arabic: "الذكر", english: "Remembrance/Dhikr", category: "concept", frequency: "common" },
  { arabic: "الدعاء", english: "Supplication/Dua", category: "concept", frequency: "common" },
  { arabic: "الزكاة", english: "Obligatory charity/Zakat", category: "concept", frequency: "common" },
  { arabic: "الصدقة", english: "Charity/Sadaqah", category: "concept", frequency: "common" },
  { arabic: "الصيام", english: "Fasting/Sawm", category: "concept", frequency: "common" },
  { arabic: "الحج", english: "Pilgrimage/Hajj", category: "concept", frequency: "common" },
  { arabic: "العمرة", english: "Lesser pilgrimage/Umrah", category: "concept", frequency: "common" },
  { arabic: "الجنة", english: "Paradise/Jannah", category: "concept", frequency: "frequent" },
  { arabic: "النار", english: "Hellfire", category: "concept", frequency: "common" },
  { arabic: "الآخرة", english: "The Hereafter", category: "concept", frequency: "frequent" },
  { arabic: "الدنيا", english: "This worldly life", category: "concept", frequency: "frequent" },
  { arabic: "يوم القيامة", english: "The Day of Judgment", category: "concept", frequency: "frequent" },
  { arabic: "يوم الحساب", english: "The Day of Reckoning", category: "concept", frequency: "common" },
  { arabic: "الملائكة", english: "The Angels", category: "concept", frequency: "common" },
  { arabic: "الكتب السماوية", english: "The Divine Books", category: "concept", frequency: "common" },
  { arabic: "الأنبياء والمرسلين", english: "The Prophets and Messengers", category: "concept", frequency: "common" },
  { arabic: "القدر", english: "Divine decree/Qadr", category: "concept", frequency: "common" },
  { arabic: "الرزق", english: "Provision/Rizq", category: "concept", frequency: "common" },
  { arabic: "البركة", english: "Blessing/Barakah", category: "concept", frequency: "common" },
  { arabic: "الهداية", english: "Guidance/Hidayah", category: "concept", frequency: "common" },
  { arabic: "النور", english: "Light/Noor", category: "concept", frequency: "common" },
  { arabic: "الرحمة", english: "Mercy/Rahmah", category: "concept", frequency: "frequent" },
  { arabic: "المغفرة", english: "Forgiveness/Maghfirah", category: "concept", frequency: "common" },
  
  // ==================== PROPHETS & FIGURES ====================
  { arabic: "النبي محمد", english: "Prophet Muhammad", category: "prophet", frequency: "frequent" },
  { arabic: "سيدنا محمد", english: "Our master Muhammad", category: "prophet", frequency: "frequent" },
  { arabic: "رسول الله", english: "Messenger of Allah", category: "prophet", frequency: "frequent" },
  { arabic: "خاتم النبيين", english: "The Seal of the Prophets", category: "prophet", frequency: "common" },
  { arabic: "نبي الله إبراهيم", english: "Prophet Ibrahim (Abraham)", category: "prophet", frequency: "common" },
  { arabic: "نبي الله موسى", english: "Prophet Musa (Moses)", category: "prophet", frequency: "common" },
  { arabic: "نبي الله عيسى", english: "Prophet Isa (Jesus)", category: "prophet", frequency: "common" },
  { arabic: "نبي الله نوح", english: "Prophet Nuh (Noah)", category: "prophet", frequency: "common" },
  { arabic: "نبي الله آدم", english: "Prophet Adam", category: "prophet", frequency: "common" },
  { arabic: "نبي الله يوسف", english: "Prophet Yusuf (Joseph)", category: "prophet", frequency: "common" },
  { arabic: "نبي الله داود", english: "Prophet Dawud (David)", category: "prophet", frequency: "common" },
  { arabic: "نبي الله سليمان", english: "Prophet Sulayman (Solomon)", category: "prophet", frequency: "common" },
  { arabic: "الصحابة", english: "The Companions", category: "prophet", frequency: "common" },
  { arabic: "أبو بكر الصديق", english: "Abu Bakr As-Siddiq", category: "prophet", frequency: "common" },
  { arabic: "عمر بن الخطاب", english: "Umar ibn Al-Khattab", category: "prophet", frequency: "common" },
  { arabic: "عثمان بن عفان", english: "Uthman ibn Affan", category: "prophet", frequency: "common" },
  { arabic: "علي بن أبي طالب", english: "Ali ibn Abi Talib", category: "prophet", frequency: "common" },
  { arabic: "أم المؤمنين", english: "Mother of the Believers", category: "prophet", frequency: "common" },
  
  // ==================== ISLAMIC MONTHS & EVENTS ====================
  { arabic: "شهر رمضان", english: "The month of Ramadan", category: "calendar", frequency: "common" },
  { arabic: "رمضان المبارك", english: "Blessed Ramadan", category: "calendar", frequency: "common" },
  { arabic: "ليلة القدر", english: "The Night of Power/Laylat al-Qadr", category: "calendar", frequency: "common" },
  { arabic: "عيد الفطر", english: "Eid al-Fitr", category: "calendar", frequency: "common" },
  { arabic: "عيد الأضحى", english: "Eid al-Adha", category: "calendar", frequency: "common" },
  { arabic: "يوم عرفة", english: "Day of Arafah", category: "calendar", frequency: "common" },
  { arabic: "ذو الحجة", english: "Dhul Hijjah", category: "calendar", frequency: "common" },
  { arabic: "المحرم", english: "Muharram", category: "calendar", frequency: "common" },
  { arabic: "يوم عاشوراء", english: "Day of Ashura", category: "calendar", frequency: "common" },
  
  // ==================== COMMON EXPRESSIONS ====================
  { arabic: "والله", english: "By Allah/I swear by Allah", category: "expression", frequency: "frequent" },
  { arabic: "بإذن الله", english: "By the permission of Allah", category: "expression", frequency: "common" },
  { arabic: "نسأل الله", english: "We ask Allah", category: "expression", frequency: "common" },
  { arabic: "اللهم اجعلنا", english: "O Allah, make us", category: "expression", frequency: "common" },
  { arabic: "اللهم أعنا", english: "O Allah, help us", category: "expression", frequency: "common" },
  { arabic: "اللهم ارزقنا", english: "O Allah, provide for us", category: "expression", frequency: "common" },
  { arabic: "اللهم اغفر لنا", english: "O Allah, forgive us", category: "expression", frequency: "common" },
  { arabic: "اللهم ارحمنا", english: "O Allah, have mercy on us", category: "expression", frequency: "common" },
  { arabic: "اللهم اهدنا", english: "O Allah, guide us", category: "expression", frequency: "common" },
  { arabic: "اللهم وفقنا", english: "O Allah, grant us success", category: "expression", frequency: "common" },
  { arabic: "اللهم احفظنا", english: "O Allah, protect us", category: "expression", frequency: "common" },
  { arabic: "اللهم بارك لنا", english: "O Allah, bless us", category: "expression", frequency: "common" },
  { arabic: "اللهم تقبل منا", english: "O Allah, accept from us", category: "expression", frequency: "common" },
  { arabic: "اللهم صل وسلم على نبينا محمد", english: "O Allah, send blessings and peace upon our Prophet Muhammad", category: "expression", frequency: "frequent" },
  { arabic: "اللهم صل على محمد", english: "O Allah, send blessings upon Muhammad", category: "expression", frequency: "frequent" },
  { arabic: "الله يهديك", english: "May Allah guide you", category: "expression", frequency: "common" },
  { arabic: "الله يعطيك العافية", english: "May Allah give you strength/wellness", category: "expression", frequency: "common" },
  { arabic: "الله يرحمه", english: "May Allah have mercy on him", category: "expression", frequency: "common" },
  { arabic: "الله يشفيك", english: "May Allah heal you", category: "expression", frequency: "common" },
  { arabic: "الله المستعان", english: "Allah is the One whose help is sought", category: "expression", frequency: "common" },
  { arabic: "لا شكر على واجب", english: "No need to thank me for a duty", category: "expression", frequency: "common" },
  { arabic: "إذا شاء الله", english: "If Allah wills", category: "expression", frequency: "common" },
  { arabic: "بفضل الله", english: "By the grace of Allah", category: "expression", frequency: "common" },
  { arabic: "نعم الله", english: "The blessings of Allah", category: "expression", frequency: "common" },
  
  // ==================== NAMES OF ALLAH ====================
  { arabic: "الرحمن", english: "The Most Gracious", category: "names_of_allah", frequency: "frequent" },
  { arabic: "الرحيم", english: "The Most Merciful", category: "names_of_allah", frequency: "frequent" },
  { arabic: "الملك", english: "The King", category: "names_of_allah", frequency: "common" },
  { arabic: "القدوس", english: "The Most Holy", category: "names_of_allah", frequency: "common" },
  { arabic: "السلام", english: "The Source of Peace", category: "names_of_allah", frequency: "common" },
  { arabic: "المؤمن", english: "The Guardian of Faith", category: "names_of_allah", frequency: "common" },
  { arabic: "المهيمن", english: "The Protector", category: "names_of_allah", frequency: "common" },
  { arabic: "العزيز", english: "The Almighty", category: "names_of_allah", frequency: "common" },
  { arabic: "الجبار", english: "The Compeller", category: "names_of_allah", frequency: "common" },
  { arabic: "المتكبر", english: "The Supreme", category: "names_of_allah", frequency: "common" },
  { arabic: "الخالق", english: "The Creator", category: "names_of_allah", frequency: "common" },
  { arabic: "البارئ", english: "The Evolver", category: "names_of_allah", frequency: "common" },
  { arabic: "الغفور", english: "The All-Forgiving", category: "names_of_allah", frequency: "frequent" },
  { arabic: "الغفار", english: "The Forgiving", category: "names_of_allah", frequency: "common" },
  { arabic: "الرزاق", english: "The Provider", category: "names_of_allah", frequency: "common" },
  { arabic: "السميع", english: "The All-Hearing", category: "names_of_allah", frequency: "common" },
  { arabic: "البصير", english: "The All-Seeing", category: "names_of_allah", frequency: "common" },
  { arabic: "العليم", english: "The All-Knowing", category: "names_of_allah", frequency: "frequent" },
  { arabic: "الحكيم", english: "The Most Wise", category: "names_of_allah", frequency: "common" },
  { arabic: "اللطيف", english: "The Subtle One", category: "names_of_allah", frequency: "common" },
  { arabic: "الخبير", english: "The All-Aware", category: "names_of_allah", frequency: "common" },
  { arabic: "الحليم", english: "The Forbearing", category: "names_of_allah", frequency: "common" },
  { arabic: "العظيم", english: "The Magnificent", category: "names_of_allah", frequency: "common" },
  { arabic: "الكريم", english: "The Most Generous", category: "names_of_allah", frequency: "common" },
  { arabic: "الرقيب", english: "The Watchful", category: "names_of_allah", frequency: "common" },
  { arabic: "المجيب", english: "The Responsive", category: "names_of_allah", frequency: "common" },
  { arabic: "الواسع", english: "The All-Encompassing", category: "names_of_allah", frequency: "common" },
  { arabic: "الودود", english: "The Most Loving", category: "names_of_allah", frequency: "common" },
  { arabic: "المجيد", english: "The Most Glorious", category: "names_of_allah", frequency: "common" },
  { arabic: "الباعث", english: "The Resurrector", category: "names_of_allah", frequency: "common" },
  { arabic: "الشهيد", english: "The Witness", category: "names_of_allah", frequency: "common" },
  { arabic: "الحق", english: "The Truth", category: "names_of_allah", frequency: "common" },
  { arabic: "الوكيل", english: "The Trustee", category: "names_of_allah", frequency: "common" },
  { arabic: "القوي", english: "The Most Strong", category: "names_of_allah", frequency: "common" },
  { arabic: "المتين", english: "The Firm", category: "names_of_allah", frequency: "common" },
  { arabic: "الولي", english: "The Protecting Friend", category: "names_of_allah", frequency: "common" },
  { arabic: "الحميد", english: "The Praiseworthy", category: "names_of_allah", frequency: "common" },
  { arabic: "الكبير", english: "The Great", category: "names_of_allah", frequency: "common" },
  { arabic: "المقيت", english: "The Nourisher", category: "names_of_allah", frequency: "common" },
  { arabic: "الحسيب", english: "The Reckoner", category: "names_of_allah", frequency: "common" },
  { arabic: "الجليل", english: "The Majestic", category: "names_of_allah", frequency: "common" },
  { arabic: "المعيد", english: "The Restorer", category: "names_of_allah", frequency: "common" },
  { arabic: "المحيي", english: "The Giver of Life", category: "names_of_allah", frequency: "common" },
  { arabic: "المميت", english: "The Taker of Life", category: "names_of_allah", frequency: "common" },
  { arabic: "الحي", english: "The Ever Living", category: "names_of_allah", frequency: "common" },
  { arabic: "القيوم", english: "The Self-Subsisting", category: "names_of_allah", frequency: "common" },
  { arabic: "الواجد", english: "The Finder", category: "names_of_allah", frequency: "common" },
  { arabic: "الماجد", english: "The Noble", category: "names_of_allah", frequency: "common" },
  { arabic: "الواحد", english: "The One", category: "names_of_allah", frequency: "frequent" },
  { arabic: "الأحد", english: "The Unique", category: "names_of_allah", frequency: "frequent" },
  { arabic: "الصمد", english: "The Eternal", category: "names_of_allah", frequency: "common" },
  { arabic: "القادر", english: "The Able", category: "names_of_allah", frequency: "common" },
  { arabic: "المقتدر", english: "The Powerful", category: "names_of_allah", frequency: "common" },
  { arabic: "الأول", english: "The First", category: "names_of_allah", frequency: "common" },
  { arabic: "الآخر", english: "The Last", category: "names_of_allah", frequency: "common" },
  { arabic: "الظاهر", english: "The Manifest", category: "names_of_allah", frequency: "common" },
  { arabic: "الباطن", english: "The Hidden", category: "names_of_allah", frequency: "common" },
  { arabic: "التواب", english: "The Acceptor of Repentance", category: "names_of_allah", frequency: "common" },
  { arabic: "المنتقم", english: "The Avenger", category: "names_of_allah", frequency: "common" },
  { arabic: "العفو", english: "The Pardoner", category: "names_of_allah", frequency: "common" },
  { arabic: "الرؤوف", english: "The Compassionate", category: "names_of_allah", frequency: "common" },
  { arabic: "مالك الملك", english: "Owner of Sovereignty", category: "names_of_allah", frequency: "common" },
  { arabic: "ذو الجلال والإكرام", english: "Lord of Majesty and Bounty", category: "names_of_allah", frequency: "common" },
  { arabic: "المقسط", english: "The Equitable", category: "names_of_allah", frequency: "common" },
  { arabic: "الجامع", english: "The Gatherer", category: "names_of_allah", frequency: "common" },
  { arabic: "الغني", english: "The Self-Sufficient", category: "names_of_allah", frequency: "common" },
  { arabic: "المغني", english: "The Enricher", category: "names_of_allah", frequency: "common" },
  { arabic: "المانع", english: "The Preventer", category: "names_of_allah", frequency: "common" },
  { arabic: "الضار", english: "The Distresser", category: "names_of_allah", frequency: "common" },
  { arabic: "النافع", english: "The Benefactor", category: "names_of_allah", frequency: "common" },
  { arabic: "النور", english: "The Light", category: "names_of_allah", frequency: "common" },
  { arabic: "الهادي", english: "The Guide", category: "names_of_allah", frequency: "common" },
  { arabic: "البديع", english: "The Incomparable", category: "names_of_allah", frequency: "common" },
  { arabic: "الباقي", english: "The Everlasting", category: "names_of_allah", frequency: "common" },
  { arabic: "الوارث", english: "The Inheritor", category: "names_of_allah", frequency: "common" },
  { arabic: "الرشيد", english: "The Righteous Guide", category: "names_of_allah", frequency: "common" },
  { arabic: "الصبور", english: "The Patient", category: "names_of_allah", frequency: "common" },
  
  // ==================== ADDITIONAL COMMON PHRASES ====================
  { arabic: "إخوتي في الله", english: "My brothers in Allah", category: "expression", frequency: "common" },
  { arabic: "أخي في الله", english: "My brother in Allah", category: "expression", frequency: "common" },
  { arabic: "أختي في الله", english: "My sister in Allah", category: "expression", frequency: "common" },
  { arabic: "في سبيل الله", english: "In the way of Allah", category: "expression", frequency: "common" },
  { arabic: "لوجه الله", english: "For the sake of Allah", category: "expression", frequency: "common" },
  { arabic: "ابتغاء مرضاة الله", english: "Seeking the pleasure of Allah", category: "expression", frequency: "common" },
  { arabic: "طاعة الله", english: "Obedience to Allah", category: "expression", frequency: "common" },
  { arabic: "معصية الله", english: "Disobedience to Allah", category: "expression", frequency: "common" },
  { arabic: "خوف الله", english: "Fear of Allah", category: "expression", frequency: "common" },
  { arabic: "حب الله", english: "Love of Allah", category: "expression", frequency: "common" },
  { arabic: "ذكر الله", english: "Remembrance of Allah", category: "expression", frequency: "common" },
  { arabic: "عون الله", english: "Help of Allah", category: "expression", frequency: "common" },
  { arabic: "توفيق الله", english: "Success from Allah", category: "expression", frequency: "common" },
  { arabic: "نعمة الله", english: "Blessing of Allah", category: "expression", frequency: "common" },
  { arabic: "فضل الله", english: "Grace of Allah", category: "expression", frequency: "common" },
  { arabic: "قدرة الله", english: "Power of Allah", category: "expression", frequency: "common" },
  { arabic: "حكمة الله", english: "Wisdom of Allah", category: "expression", frequency: "common" },
  { arabic: "عدل الله", english: "Justice of Allah", category: "expression", frequency: "common" },
  { arabic: "سنة النبي", english: "Sunnah of the Prophet", category: "expression", frequency: "common" },
  { arabic: "هدي النبي", english: "Guidance of the Prophet", category: "expression", frequency: "common" },
  { arabic: "سيرة النبي", english: "Biography of the Prophet", category: "expression", frequency: "common" },
  { arabic: "حديث نبوي", english: "Prophetic tradition", category: "expression", frequency: "common" },
  { arabic: "الكتاب والسنة", english: "The Book (Quran) and Sunnah", category: "expression", frequency: "common" },
  { arabic: "أهل السنة والجماعة", english: "People of the Sunnah and the Community", category: "expression", frequency: "common" },
  { arabic: "السلف الصالح", english: "The Righteous Predecessors", category: "expression", frequency: "common" },
  { arabic: "العلماء", english: "The scholars", category: "expression", frequency: "common" },
  { arabic: "طالب العلم", english: "Student of knowledge", category: "expression", frequency: "common" },
  { arabic: "المسجد", english: "The mosque", category: "expression", frequency: "common" },
  { arabic: "بيت الله", english: "House of Allah", category: "expression", frequency: "common" },
  { arabic: "المسجد الحرام", english: "The Sacred Mosque (Mecca)", category: "expression", frequency: "common" },
  { arabic: "المسجد النبوي", english: "The Prophet's Mosque (Medina)", category: "expression", frequency: "common" },
  { arabic: "المسجد الأقصى", english: "Al-Aqsa Mosque (Jerusalem)", category: "expression", frequency: "common" },
  { arabic: "الكعبة المشرفة", english: "The Noble Kaaba", category: "expression", frequency: "common" },
  { arabic: "القبلة", english: "Direction of prayer/Qibla", category: "expression", frequency: "common" },
];

// Function to seed all phrases
export async function seedIslamicPhrases() {
  const { translationCacheService } = await import("./translation-cache");
  
  console.log(`Seeding ${islamicPhrasesData.length} Islamic phrases...`);
  const added = await translationCacheService.seedPhrases(islamicPhrasesData);
  console.log(`Successfully seeded ${added} phrases`);
  
  return added;
}
